[package]
name = "Galois_Theory"
version = "0.1"
lean_version = "leanprover-community/lean:3.19.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "6a5241f2bf5e9a027b4295fcfae2cd2b32740465"}
