[package]
name = "Galois_Theory"
version = "0.1"
lean_version = "leanprover-community/lean:3.9.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "94ff59ad7efdcf0ae51809c2ee0dfd0ae605d249"}
