[package]
name = "Galois_Theory"
version = "0.1"
lean_version = "leanprover-community/lean:3.14.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "2deb6b46fc5768c9226289feec1b32c7028a135c"}
